@hostname = localhost
@port = 7071
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name step1
POST http://{{host}}/api/call_openai?question=what teams are in F1?
content-type: {{contentType}}

[
  {
    "Role": "system",
    "Text": "You are a helpful assistant on motorsport."
  },
  {
    "Role": "user",
    "Text": "What can you help me with?"
  }
]

###

@messages = {{step1.response.body.$}}

# @name step2
POST http://{{host}}/api/call_openai?question=How are the drivers?
content-type: {{contentType}}

{{messages}}


