@hostname = localhost
@port = 7071
@host = {{hostname}}:{{port}}
@contentType = application/json

###

@question = "Summerize the Corvus document only return the json object"

# @name docsum1
POST https://demo-doc-extract-mwg.azurewebsites.net/api/call_openai?code=DKiSzxj3f2X9fvG63oQPHF3WLReHy1uxp3Qb9-zTCOlWAzFuylwGAA%3D%3D&question={{question}}
content-type: {{contentType}}

###

@question = "change to csv format to load into excel"

@doc_sum1 = {{docsum1.response.body.$}}

# @name docsum2
POST https://demo-doc-extract-mwg.azurewebsites.net/api/call_openai?code=DKiSzxj3f2X9fvG63oQPHF3WLReHy1uxp3Qb9-zTCOlWAzFuylwGAA%3D%3D&search_index=vector_index2&question={{question}}
content-type: {{contentType}}

{{doc_sum1}}